### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForRelease'. > java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by huizai0613** [mogujie/ThinRPlugin#3]
![image](https://cloud.githubusercontent.com/assets/5644264/20203837/aecdba1a-a805-11e6-96b8-cb3af922e1d8.png)加上之后,打签名包 出错

**Comment by nEdAy** [comment]
Error:Execution failed for task ':app:transformClassesWithDexForRelease'.
> java.lang.NullPointerException (no error message)

**Comment by tanranran** [comment]
+1

**Comment by Lerist** [comment]
+1

**Comment by androidmalin** [comment]
+1

**Comment by farmerjohngit** [comment]
可以在执行gradle 命令时加上--stacktrace ，如果报错堆栈如下，

`Caused by: java.lang.NullPointerException
        at com.android.builder.core.DefaultManifestParser.<init>(DefaultManifestParser.java:56)
        at com.mogujie.thinR.ContextProvider.getManifestPackage(ContextProvider.groovy:84)
        at com.mogujie.thinR.ContextProvider.this$2$getManifestPackage(ContextProvider.groovy)
        at com.mogujie.thinR.ContextProvider.getPackageName(ContextProvider.groovy:76)
        at com.mogujie.thinR.ContextProvider.getRClassDir(ContextProvider.groovy:88)`

请使用最新版的thinR插件(0.0.2)
